### ISSUE TITLE
It's time to get some bugs squashed

### ISSUE THREAD

**Issue by Goldaracena** [heqro/stupid-simple-launcher#16]
Hi,

Version 1.9.2 has just dropped. It adds some features, such as changing the background color. This is a daring feature and it's possible some things may have broken down. As far as I could check, nothing blew up on my end. I am already in the process of writing unit tests, but I still have a long, long way to go.

Thus, if you see something off, please note it here and/or open an issue.

Thank you very much.

**Comment by Blad3forc3** [comment]
Everything looks fine to me here. Nothing has broken down at all. I would request that when you select to paginate the applications that the mouse wheel also scrolls through the different pages as well as being able to click the pages icons with the mouse

**Comment by cipricus** [comment]
Hi, I have a question that maybe is not widget-specific, but just in case: is there a way to move the favorites icons and change their order, other than removing and adding again? -- 
I have used Tiled Menu before this, and I've got quite used to the free movement of "pinned" apps on the grid. I think this is a general problem with all widgets that have and share  favorites, while the Tiled Menu's pinned apps is a different thing altogether. But maybe I'm missing something here..

**Comment by Goldaracena** [comment]
Each widget has their own implementation of dragging and dropping because Qt does not have one. In this widget's case, you have to press and hold for around half a second and then you can move the favorite application alongside your favorites bar.

**Comment by cipricus** [comment]
Oh, I see, so that cannot be done on the grid, just on the bar! (And because many widgets don't have a separate bar, that cannot be done there!)
On the other hand, please note that because that can only be done with the mouse, and because t[he mouse cannot be used on the favorites bar to scroll or change](https://github.com/heqro/stupid-simple-launcher/issues/26) between visible and hidden apps (hidden when they are more than what the bar can show), this movement is not possible: for example, if on my configuration I have more than 10 favorites, let's say 15, and I add a new one (e.g. LOWriter), the 16th will be hidden and accessible with the keys. If I want to put it first, I will be able to move it with the mouse but only  up to the 11th position (first in the hidden part of the list).

![image](https://user-images.githubusercontent.com/3447868/213121471-322ebc3b-e32d-4d47-a6fe-776c8d887e7a.png)

The workaround is to remove and add back an app that I want on the second half of the favorites list, which will push the LOWriter icon up onto the first half.
