### ISSUE TITLE
UX/UI Suggestions

### ISSUE THREAD

**Issue by N-Upchurch** [heqro/stupid-simple-launcher#17]
Hi there, I hope you don't mind, but I have put together some suggestions that I believe will improve the user experience for this launcher. 

![Page 1](https://user-images.githubusercontent.com/8893713/178822980-54243194-dd27-460c-b036-6dcbb8787564.png)

![Page 2](https://user-images.githubusercontent.com/8893713/178822976-470b34f0-5383-448e-8ce3-1cd9b47d6d26.png)

1. Increased margins between app icons to reduce visual clutter.
2. Increased margins between the screen edges and the widget elements (increased whitespace, so to speak) to help the user identify key elements, reduce visual clutter, and help establish visual hierarchy in combination with other suggestions. This will also visually establish that the app icon grid and the categories are related / part of the same group, and in combination with other suggestions, will help the search bar to not feel off-center.
3. Decreased space between categories and the app icon grid to establish them as related.
4. Large top and bottom margins around the search input. This will help direct user attention to this element first, ensuring that the user understands the search functionality at the outset.
5. Larger top and bottom margins surrounding the session control bar. This will visually establish the bar as a separate entity to the app icon grid. 
6. Implementation of a scroll bar to indicate to the user that there are more items accessible via the scroll wheel.
7. In the case that the user has enabled the favorites bar, it should have large top and bottom margins, establishing it as a separate entity to the app grid and categories (not illustrated).
8. Smooth scrolling, because it makes for a more natural, comfortable feeling interaction.

Thanks so much for your work in making this widget; I love the direction!

**Comment by Goldaracena** [comment]
Hi, thank you for your ideas. I have been playing with a few of them for a while and implemented some of them. However, a new version per se should not appear anytime soon because there are still things to do in my end. Let me get the ideas I implemented in the first place:

1. I have been messing around values in here, I hope to get something concrete in the following release.
6. This one was planned then scrapped somewhere down the line, up until I found the right stackOverflow post to finally refer to. It's already in a separate branch and will be in the next release once 

Moving on... number 8: as far as I can tell, there is nothing already built to get smooth scrolling in QML. Each KDE application that tries to implement anything remotely similar to smooth scrolling does it in its own, particular, way. I will hold up until some standardized component shows up.

I will keep trying to fiddle with all the ideas related to the margins. I am using a 1920x1080 14.1'' laptop, so if I am to use big margins, the applications grid is guaranteed to have a minimum of one row less. This gets at odds with the functionality/information I expect to get at first glance.

Lastly, I don't think the idea of decreasing the space between the grid and the categories is something I see myself trying to do. I intend on using this menu with a 2-in-1 laptop, so using my thumbs for changing category is something I would like to do. Making the categories list too close to the grid jeopardizes this workflow.

Cheers
