### ISSUE TITLE
Bug with the category icons.

### ISSUE THREAD

**Issue by Tuxman2** [heqro/stupid-simple-launcher#2]
Hello,

After increasing the size of the icons, the category icons are too big. I try to decrease the size of the icons but nothing happens for the category icons. They are still too big and they are displayed only. Here is a picture of the issue:

![CategoriesIcons](https://user-images.githubusercontent.com/23556606/139669440-ca8ba376-529b-4c44-8424-8d9f438de0af.jpg)

Note: size of the icons = 80. Blur for background is activate. Icon theme: Uos-Dark [deepin v20] from kde store.

Thanks.

**Comment by Goldaracena** [comment]
Could confirm by downloading the corresponding icon pack. It seems that the icon pack you mentioned doesn't have each and every size, so it would misbehave when showing them at the categories sidebar. The way to fix it resorted to hardcoding the icon's height and width. I'm not a big fan of that, but then again it's the easiest way to fix the issue (instead of calling out each and every icon package's designer).

I just pushed a fix to Github and Pling should have updated their copy of the menu by now, could you confirm it works on your end?

**Comment by Tuxman2** [comment]
Thanks.

I will check with another icon pack. I will test your new version later. ;-)

Regards.

**Comment by Tuxman2** [comment]
Ok, it's good. the category icons are good now. I also changed the icon pack. I will do some suggestions to you later. 

Regards.
