### ISSUE TITLE
Upgraded to kde neon 22.04 and the customize categories sidebar size cannot be made smaller as it used to be

### ISSUE THREAD

**Issue by Blad3forc3** [heqro/stupid-simple-launcher#20]
After upgrading to 22.04 i cannot change the customize height categories sidebar size to a setting i used to have on 21.04. The menu has defaulted to the minimum space you can set but the size between category names is too large

**Comment by Goldaracena** [comment]
I'm afraid it won't be until next year that I may get back to this project.

**Comment by Blad3forc3** [comment]
Thats a shame for some reason 22.04 has borked having the ability to make the category size smaller on this menu. Tried copying over my old settings from 21.04 but it doesnt have the same category height.
As per your quote on the KDE Store page

[heqro](https://store.kde.org/u/heqro)
•11 months ago
I clearly did an oopsie. The smallest height option is now sensibly smaller, but for some reason the fonts will clip outside the smallest possible height. Manually setting the font size to fit will work.

**Comment by Goldaracena** [comment]
I can't even my own menu to work in my Kubuntu 22.04 installation. Plasmoid development is impossible to get right because it relies on the system libraries. 

There is no estimation as when or if I will try to get this to work, but as of now I want to prioritize my maths career. At least this one does not rely on my distro packaging stuff properly! :)

**Comment by Blad3forc3** [comment]
Could you tell me where to change this setting i could do it myself

**Comment by Goldaracena** [comment]
The setting for the default categories button height is found under contents/config/main.xml, perhaps making that value lower may work, perhaps it may make everything look awful

**Comment by Blad3forc3** [comment]
Found it and works great, thanks heqro! Good luck in your exams!

**Comment by Goldaracena** [comment]
Thank you very much, I am answering as I study :)
Closing the thread; do not hesitate to write if there's any additional information you think you'd need.

**Comment by Blad3forc3** [comment]
This has stopped working with the lastest update and also the setting to change the category size height doesnt go as small as it used to

**Comment by Goldaracena** [comment]
Can you check now if the category size height slider can go as small as it used to?  It works on my end, but I am awaiting confirmation to upload to the KDE Store.

**Comment by Blad3forc3** [comment]
Yes the updated version from git makes them smaller again using the slider. Only problem is the icon sizes in general don't change size.

Edit..i mean when changing from size 156 to 148 the icon vastly reduces size

**Comment by Goldaracena** [comment]
Okay, but that is relative to the Applications menu rather than the Categories sidebar. I will get around that in a separate moment.

**Comment by Goldaracena** [comment]
> Only problem is the icon sizes in general don't change size.

I have added a new tab for this option. This feature is now present on the KDE Store version.

![Screenshot_20230118_121037](https://user-images.githubusercontent.com/58432067/213156721-c1e4d32d-49ef-40fa-b13b-3b0a446df8a4.png)

This tab allows you to live preview the application grid entries when you make changes to it. This feels more reasonable than micromanaging a spinbox and toggling in and out of the menu to see if the new number did the trick.

About the icon itself jumping sizes: I don't think that's something that's up to me so much as it is up to the icon packager. For instance, this issue was already present with the categories slider:

![Screenshot_20230118_121757](https://user-images.githubusercontent.com/58432067/213158185-e9dcd179-2909-4e8d-b6b5-36982ce242b3.png)

Just notice how much it takes the icon to actually stretch itself to fit the total height:


![Screenshot_20230118_121859](https://user-images.githubusercontent.com/58432067/213158453-369274b1-8080-40b7-8dea-f5606a10927e.png)

I believe that icons are packaged in only certain sizes (64px, 128px, etc) and that's why the size changes are not smooth, but rather jumpy.
