### ISSUE TITLE
Add file search - based on krunner/Plasma search

### ISSUE THREAD

**Issue by cipricus** [heqro/stupid-simple-launcher#21]
Incredibly, this beautiful and clever launcher seems to lack the krunner integration so that not just recent files but  indexed files can be searched and accessed, something present in all default launchers.

**Comment by Goldaracena** [comment]
I want to ensure you with this message that I will eventually get it done. 

I have not had the time to commit to keep developing this plasmoid for quite a while, but will get my hands dirty as soon as I can. I want to rethink most of the plasmoid because of performance reasons, so this may take a while.

**Comment by cipricus** [comment]
I have come back to your plasmoid in spite of my need for quick access to recent files because I like it too much overall.

**Comment by Goldaracena** [comment]
I have just pushed a fix towards that, could you please download the newest version to check if it works now?

**Comment by cipricus** [comment]
It works! Thanks!

**Comment by cipricus** [comment]
Hi, after the change I have started to use it and because I don't know if a separate issue would be advisable, I am simply asking here: what exactly is the ribbon with icons that stays unchanged and how can it be edited?

![image](https://user-images.githubusercontent.com/3447868/212962308-0ed677f5-87c8-41ef-b97d-e351db96b127.png)
