### ISSUE TITLE
Feature request: add option for categories icons size and categories ribbon length

### ISSUE THREAD

**Issue by cipricus** [heqro/stupid-simple-launcher#25]
![image](https://user-images.githubusercontent.com/3447868/213105339-03f6eb01-4d5d-4903-b555-c5022ea6259f.png)

On a medium-sized laptop, without the names, categories are small, the icon size should be adjustable. Their panel/ribbon is too short, and we need to scroll for the last item, which is odd.

**Comment by Goldaracena** [comment]
Category icon size is already adjustable. This option is found under "Categories sidebar" by checking the "Customize categories" option. A live preview of a dummy category will then appear. You can mess up with this dummy category by dragging the handlers alongside the X and Y axis. 

![Screenshot_20230118_120741](https://user-images.githubusercontent.com/58432067/213156263-7df7c600-beb6-4dda-9c29-c4537d0d6fa3.png)

This feature has been polished a bit in the master version with respect to the already existing version found in KDE Store.

**Comment by cipricus** [comment]
> alongside the X and Y axis.

Thanks!

**Comment by cipricus** [comment]
Could the category bar/ribbon also be longer? With bigger icons, the initial problem gets bigger for that part.

**Comment by Goldaracena** [comment]
This is a topic I've discussed with other users. I don't think this can be done easily because it may look weird when there is enough room for all the categories. It would look like the following screenshot but just with the list appearing from the very top instead:

![Screenshot_20230118_144512](https://user-images.githubusercontent.com/58432067/213187429-86787b1a-d1f2-4ad1-8d0b-84eae457cd18.png)

I will try to take a look at that issue from time to time.

**Comment by cipricus** [comment]
It looks fine. In fact, I have also found a midway, the right icon size that makes the scrollbar disappear.
